name: Quality Assurance
on: [pull request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: stats_core
          POSTGRES_USER: stats_core
          POSTGRES_PASSWORD: stats_core

    steps:
      - users: actions/checkout@v2

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.2

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
           STATS_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
           STATS_CORE_SETTING_LOCAL_SETTINGS_PATH: './stats_core/project/settings/templates/settings.github.py'
