name: Continuous Integration

on:
  push:
    branches:
      - main  # Change this to your main branch name

concurrency:
  group: main  # Change this to match your main branch name
  cancel-in-progress: true

jobs:
  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/pr.yml

  deploy:
    name: Deploy
    needs: quality-assurance
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH Directory and Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          cat > ~/.ssh/config <<EOF
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            LogLevel ERROR
            StrictHostKeyChecking no
          EOF

      - name: Verify SSH Configuration
        run: |
          ls -al ~/.ssh
          cat ~/.ssh/config
          ssh -T target  # Test SSH connection to target

      - name: Run deploy
        run: |
          ssh target "cd Stats-Test/ && docker-compose down && git pull && docker-compose build && docker-compose up -d --force-recreate"
